### PR TITLE
Merged mods from MacrosBlackD and adds configuration for mods

### PR DESCRIPTION
**Pull request by macrosblackd**
Merges all my mods & pulling cecil from nuget.

Also adds configuration settings via app.config. All settings are vanilla default except for run speed.

### CODE REVIEW

**Comment by kevinmurphy678** [comment]
Nice. I'll test it out then probably add a new release!

**Comment by kevinmurphy678** [comment]
Is the configuration editable from outside visual studio? Im not sure how it works

**Comment by macrosblackd** [comment]
Yes, when you package the release, make sure you include the .config file, all the settings are bundled into that.

**Comment by kevinmurphy678** [comment]
New patch 1.03. You might want to check to see if your hooks still work

**Comment by kevinmurphy678** [comment]
Ive released the new version anyway, time scale still works but I don't know about fishing. You'll have to let me know

**Comment by macrosblackd** [comment]
All seem to be working

**Pull request merged**
